defaults:
  - config_schema
  - adsb_backend: adsbexchange
  - notification_backend: twitter_selenium
  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

airplane:
  icao_hex_id:
  registration:

